# Generated by Django 4.0.6 on 2022-07-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='q10',
        ),
        migrations.RemoveField(
            model_name='form',
            name='q9',
        ),
    ]
